### PR TITLE
Stack update

### PR DESCRIPTION
**Pull request by easel**
Updating a bunch of dependencies gets things _almost_ working on JDK8, with the exception of a few errors like the following: `metascala.InternalVmException: java.lang.AssertionError: assertion failed: method cannot be native: java/lang/StrictMath log(D)D`. Any thoughts?

### CODE REVIEW

**Comment by lihaoyi** [comment]
It probably means someone is calling that as a VM intrinsic, and it hasn't been defined as one. Presumably it didn't exist in JDK7.

**Comment by lihaoyi** [comment]
You'll need to add it to the list of intrinsics below and provide a definition in the interpreter w.r.t. what that function does

https://github.com/lihaoyi/Metascala/blob/master/src/main/scala/metascala/natives/Default.scala

**Comment by easel** [comment]
Interesting, so apparently with JDK8 a bunch of the core stuff like Class.forName got moved into native methods?

**Comment by lihaoyi** [comment]
No clue =P

**Comment by easel** [comment]
Ok it looks like BigDecimal started using java.lang.StrictMath.log() and they changed the signature a bit for Class.forName. Those changes plus a sprinkle of additional heap and I'm down to a bunch of failures like 

```
[info] MetacircularTest:
[info] - sqrtFinder *** FAILED ***
[info]   metascala.UncaughtVmException: java.lang.Exception: Can't find metascala/features/controlflow/Loops
[info]   at metascala.rt.Thread.throwException(Thread.scala:360)
[info]   at metascala.rt.Thread.step(Thread.scala:291)
[info]   at metascala.rt.Thread.invoke(Thread.scala:425)
[info]   at metascala.VM.invoke(VM.scala:182)
[info]   at metascala.VM.exec(VM.scala:200)
[info]   at metascala.Util$DoStuff.test(Util.scala:88)
[info]   at metascala.full.MetacircularTest$$anonfun$1.apply$mcV$sp(MetacircularTest.scala:18)
[info]   at metascala.full.MetacircularTest$$anonfun$1.apply(MetacircularTest.scala:18)
[info]   at metascala.full.MetacircularTest$$anonfun$1.apply(MetacircularTest.scala:18)
[info]   at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
```

**Comment by easel** [comment]
I think the issue is related to updating SBT. Using getClass.getClassLoader, we're getting a classLoader that fails to find Loops.class, for whatever reason. Interestingly, flipping to `getClass.getClassLoader.getResource` shifts the "not found" file to `metascala/full/MetacircularTest$$anonfun$1$$anonfun$apply$mcV$sp$1` and using 

`val loaded = Option(getClass.getClassLoader.getResourceAsStream(slashName)).orElse(
      Option(getClass.getResourceAsStream(slashName))
)` 

gets even further, failing out trying to load stuff from jars with `metascala.UncaughtVmException: metascala.UncaughtVmException: java.lang.InternalError: could not load jarsystem protocol handler`

**Comment by lihaoyi** [comment]
Which test is failing? What you are seeing is Metascala blowing up at the meta-meta-level: it's running Metascala1 interpreting Metascala2 interpreting some some arbitrary code, and for some reason the `some arbitrary code` is crashing.

Presumably some bug in Metascala is causing a difference in behavior (i.e. bug) at some level, which is causing the `some arbitrary code` to crash. Whether that difference-in-behavior is at the point of crash, or some time earlier, is something for you to find out.

Also, which meta-level is misbehaving? Who knows! That's part of what makes debugging Metascala fun :stuck_out_tongue:

There are a variety of ways you can debug this. 
- Trace the execution bytecode by bytecode by uncommenting the lines [here](https://github.com/lihaoyi/Metascala/blob/cf9c452195f3a2e4d127e28ec4aba88e8220925f/src/main/scala/metascala/rt/Thread.scala#L52). 
- Add an if-statement and counter (I think there's already one) if you want to ignore bytecodes up to a certain point (first 100k? 400k?), because meta-interpretation makes the outer Metascala interprete a _lot_ of bytecodes! You could also probably implement some kind of "what meta level am I" hook, to let you only print things at one meta-level of interest.
- Look at the stack trace, which IIRC _should_ in this case contain no less than three stacks: the stack, the meta-stack, and the meta-meta-stack. That could give you some indication of what is happening. These should have line numbers too.
- Put `println` in code anywhere, including code that's being executed at the meta- or meta-meta- level, and the lines printed will IIRC be prefixed with something that indicates the meta-level they're being printed at. Might be hard if the thing that's blowing up is in the standard library, but putting more prints inside Metascala itself could reveal to you the behavior of the code it's interpreting (similar to the code you can uncomment out above). What allocations are happening? What intrinsics are being called? Just put a `println` in the right spot and find out.
- You can try dumping the binary heap at various meta-levels and see what it contains. The commented-out code above already does that for small heaps, but it grows massive if you're doing meta-interpretation.
- Regardless of what you do, you _should_ try minimizing the failure. So running Metascala inside Metascala fails, no big deal. Can you run some trivial code inside Metascala? ASM? The various standard library functions Metascala? One of these things is misbehaving, and this will help narrow down which one.

I haven't looked into this code for two years now, but you've signed yourself up for quite a challenge. 

May the force be with you =)

**Comment by lihaoyi** [comment]
https://github.com/lihaoyi/Metascala/commit/2f9d792bdac052e520c6c5488f5da51b21313f33 should get Metascala working on Java8/Scala2.11/SBT0.13.15. There's one regression I haven't had time to fix (`metascala.full.MetacircularTest.bubbleSort`) but now that most things are running feel free to poke at it!

**Pull request closed without merging**
